# Generated by Django 4.0.1 on 2022-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactDetailModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(help_text='Enter FullName', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email id', max_length=100)),
                ('contact', models.BigIntegerField(help_text='Enter Mobile Number')),
                ('subject', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'user_contact_details',
            },
        ),
        migrations.DeleteModel(
            name='StudentRegisterModel',
        ),
    ]
