# Generated by Django 4.0.1 on 2022-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usercontactdetailmodel_delete_studentregistermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactdetailmodel',
            name='subject',
            field=models.CharField(help_text='Enter Password', max_length=100, null=True),
        ),
    ]
