# Generated by Django 4.0.3 on 2022-03-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSupervisorModel',
            new_name='SupervisorModel',
        ),
        migrations.RenameField(
            model_name='supervisormodel',
            old_name='user_id',
            new_name='supervisor_id',
        ),
        migrations.AlterModelTable(
            name='supervisormodel',
            table='supervisor_details',
        ),
    ]
