# Generated by Django 4.0.3 on 2022-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_addsupervisormodel_supervisormodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venuename', models.CharField(help_text='Enter FullName', max_length=100)),
            ],
            options={
                'db_table': 'Venue_details',
            },
        ),
    ]
