# Generated by Django 4.0.3 on 2022-03-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentregistermodel',
            table='user_details',
        ),
    ]
