# Generated by Django 4.0.3 on 2022-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_studentregistermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookSlotModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter FullName', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email id', max_length=100)),
                ('contact', models.BigIntegerField(help_text='Enter Mobile Number')),
                ('Registration_id', models.IntegerField(help_text='Enter Registrationid', max_length=100)),
                ('Passport_id', models.IntegerField(help_text='Enter Passportid', max_length=100)),
                ('Ds_id', models.IntegerField(help_text='Enter Dsid', max_length=100)),
            ],
            options={
                'db_table': 'user_booking_details',
            },
        ),
    ]
