# Generated by Django 4.0.3 on 2022-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_userbookslotmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistermodel',
            name='contact',
            field=models.BigIntegerField(help_text='Enter Mobile Number', null=True),
        ),
    ]
