# Generated by Django 4.0.3 on 2022-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupAddSlotModel',
            fields=[
                ('Slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter FullName', max_length=100)),
                ('date', models.DateField(help_text='Enter Mobile Number')),
                ('time', models.TimeField(help_text='Enter Email id', max_length=100)),
                ('type', models.CharField(help_text='Enter Password', max_length=100)),
                ('duration', models.CharField(help_text='Enter Password', max_length=100)),
                ('venue', models.CharField(help_text='Enter Password', max_length=100)),
                ('documents', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'slot_details',
            },
        ),
    ]
