# Generated by Django 4.0.3 on 2022-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supaddslotmodel',
            name='sup_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
