# Generated by Django 4.0.3 on 2022-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisorapp', '0002_supaddslotmodel_sup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supaddslotmodel',
            name='booked_by',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supaddslotmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
