# Generated by Django 4.0.3 on 2022-03-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisorapp', '0003_supaddslotmodel_booked_by_supaddslotmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supaddslotmodel',
            name='booked_by',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supaddslotmodel',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=50, null=True),
        ),
    ]
